version: "3"

services:
  db_node_domain:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress 
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    container_name: wordpress_db

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "${APP_PORT}:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

#database
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}   
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

#phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db        
      MYSQL_ROOT_PASSWORD: password

#wordpress
  wordpress:
    depends_on:
      - db_node_domain
    image: wordpress:latest
    ports:
      - "7777:80"
    expose:
      - "80"
    restart: always
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      WORDPRESS_DB_HOST: db_node_domain:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    container_name: wordpress
volumes:
  db_data: {}

networks:
  default:
    external:
      name: nginx-proxy

    