version: "3.0"
#duongduonglasomot
services:
  duongduong:
    image: wordpress:latest
    environment:
      VIRTUAL_HOST: duongduonglaso.mot
      VIRTUAL_PORT: 7777
    expose:
      - "7777"
    restart: always
    networks: 
      - wpsite
networks:
  default:
    external:
      name: nginx-proxy      
      
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx-proxy 

  #variables     
  wordpress:
    container_name: 'wp'
    build: .
    restart: unless-stopped
    links:
      - mysql
    enviroment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      -80:80
 #database
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress 
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
 #phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db        
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite  
 # wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "7777:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress 
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data:
